src/main/java/com/andaily/domain/developer/Backlog.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.developer.operation.ScrumSecurityChecker;
import com.andaily.domain.developer.project.Project;
import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.User;
import com.andaily.infrastructure.support.LogHelper;
import com.andaily.web.context.BeanProvider;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Date: 13-8-3
 *
 * @author Shengzhao Li
 */
public class Backlog extends AbstractDomain {

    private static LogHelper log = LogHelper.create(Backlog.class);
    private transient BacklogRepository backlogRepository = BeanProvider.getBean(BacklogRepository.class);
    private transient SprintRepository sprintRepository = BeanProvider.getBean(SprintRepository.class);

    private SprintPriority priority = SprintPriority.DEFAULT;

    private String content;

    //backlog number, unique
    private int number;

    private BacklogType type = BacklogType.NEEDS;

    //If the backlog do not refer an exist sprint, the value is null
    private Sprint sprint;

    private User creator;

    // update the field value when create Sprint
    private User joinSprintUser;
    private Date joinSprintTime;

    // The field max hours is 16
    //Unit: hour
    private int estimateTime;

    private Project project;

    //documents
    private List<BacklogDocument> documents = new ArrayList<>();

    public Backlog() {
    }

    public Backlog(SprintPriority priority, String content, BacklogType type) {
        this.priority = priority;
        this.content = content;
        this.type = type;
    }

    public int number() {
        return number;
    }

    public Backlog number(int number) {
        this.number = number;
        return this;
    }

    public Backlog updateCreator(User creator) {
        this.creator = creator;
        return this;
    }

    public SprintPriority priority() {
        return priority;
    }

    public String content() {
        return content;
    }

    public BacklogType type() {
        return type;
    }

    public Sprint sprint() {
        return sprint;
    }

    public User creator() {
        return creator;
    }

    public User joinSprintUser() {
        return joinSprintUser;
    }

    public Date joinSprintTime() {
        return joinSprintTime;
    }

    public Backlog updateContent(String content) {
        this.content = content;
        return this;
    }

    public Backlog updateJoinSprintTime(Date joinSprintTime) {
        this.joinSprintTime = joinSprintTime;
        return this;
    }

    public Backlog updateSprint(Sprint sprint) {
        this.sprint = sprint;
        return this;
    }

    public Backlog updateType(BacklogType type) {
        this.type = type;
        return this;
    }

    public Backlog updatePriority(SprintPriority priority) {
        this.priority = priority;
        return this;
    }

    public void saveOrUpdate() {
        if (isNewly()) {
            backlogRepository.saveBacklog(this);
        } else {
            backlogRepository.updateBacklog(this);
        }
    }

    public Backlog archive() {
        ScrumSecurityChecker.checkBacklogReferSprint(this, false);
        this.archived(true);
        log.debug(SecurityUtils.currUser().displayName() + " archive the backlog [" + this.guid + "]");
        return this;
    }

    @Override
    public String toString() {
        return "{" +
                "id='" + id() + '\'' +
                ",content='" + content + '\'' +
                '}';
    }

    public int estimateTime() {
        return estimateTime;
    }

    public Backlog updateEstimateTime(int estimateTime) {
        this.estimateTime = estimateTime;
        return this;
    }

    public Project project() {
        return project;
    }

    public Backlog updateProject(Project project) {
        this.project = project;
        return this;
    }

    public List<BacklogDocument> documents() {
        return documents;
    }

    /**
     * Amount of the task refer the backlog
     *
     * @return Amount of task
     */
    public int referencedSprintTasks() {
        return sprintRepository.totalSprintTasksOfBacklog(this);
    }
}

src/main/java/com/andaily/domain/developer/BacklogDocument.java
package com.andaily.domain.developer;

import com.andaily.domain.developer.commons.Document;
import com.andaily.domain.developer.commons.GeckoFile;

/**
 * @author Shengzhao Li
 */
public class BacklogDocument extends Document {

    private Backlog backlog;

    public BacklogDocument() {
    }

    public BacklogDocument(Backlog backlog, GeckoFile file) {
        super(file);
        this.backlog = backlog;
    }

    @Override
    public void saveOrUpdate() {
        if (isNewly()) {
            file.saveOrUpdate();
            file = commonsRepository.findGeckoFileByGuid(file.guid());
            commonsRepository.saveBacklogDocument(this);
        } else {
            throw new UnsupportedOperationException("Update BacklogDocument is un-supported");
        }
    }

    public Backlog backlog() {
        return backlog;
    }
}

src/main/java/com/andaily/domain/developer/BacklogRepository.java
package com.andaily.domain.developer;

import com.andaily.domain.developer.project.Project;
import com.andaily.domain.shared.Repository;
import com.andaily.domain.user.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * Date: 13-8-5
 *
 * @author Shengzhao Li
 */
public interface BacklogRepository extends Repository {

    Backlog findByGuid(String guid);

    void saveBacklog(Backlog backlog);

    void updateBacklog(Backlog backlog);

    List<Backlog> findAvailableBacklogs(String projectGuid);

    void updateSprintBacklogs(@Param("sprintGuid") String sprintGuid, @Param("backlogGuids") List<String> backlogGuids, @Param("user") User user);

    void cleanBacklogsSprint(@Param("backlogs") List<Backlog> backlogs);

    List<Backlog> findSprintBacklogs(String sprintGuid);

    List<Backlog> findOverviewBacklogs(Map<String, Object> map);

    int totalOverviewBacklogs(Map<String, Object> map);

    List<Backlog> findUnusedBacklogsByProject(Project project);

    int maxBacklogNumber();
}

src/main/java/com/andaily/domain/developer/BacklogType.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-5
 *
 * @author Shengzhao Li
 */
public enum BacklogType {

    NEEDS("Needs", "需求"),
    BUGS("Bug", "Bug"),
    SUGGESTIONS("Suggestions", "建议");

    private String label;
    private String cnLabel;

    private BacklogType(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            return user.language().isChinese() ? cnLabel : label;
        }
        return label;
    }
}

src/main/java/com/andaily/domain/developer/ScrumComment.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.user.Developer;

import java.util.Date;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public class ScrumComment extends AbstractDomain {

    //who
    private Developer developer;
    //when
    private Date commentTime;
    //do what
    private String content;

    public ScrumComment() {
    }

    public ScrumComment(Developer developer, Date commentTime, String content) {
        this.developer = developer;
        this.commentTime = commentTime;
        this.content = content;
    }

    public Developer developer() {
        return developer;
    }

    public Date commentTime() {
        return commentTime;
    }

    public String content() {
        return content;
    }
}

src/main/java/com/andaily/domain/developer/ScrumRepository.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.Repository;

/**
 * Date: 13-9-23
 *
 * @author Shengzhao Li
 */
public interface ScrumRepository extends Repository {

    void saveComment(ScrumComment comment);

    ScrumComment findCommentByGuid(String guid);
}

src/main/java/com/andaily/domain/developer/SprintMeeting.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.web.context.BeanProvider;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public class SprintMeeting extends AbstractDomain {

    private transient SprintRepository sprintRepository = BeanProvider.getBean(SprintRepository.class);

    private Date meetingDate;
    private String content;

    private SprintMeetingType type;

    //The developers which join the meeting
    private List<SprintMeetingDeveloper> joinDevelopers = new ArrayList<SprintMeetingDeveloper>();

    private Sprint sprint;

    public SprintMeeting() {
    }

    public SprintMeeting(Date meetingDate, SprintMeetingType type, String content) {
        this.meetingDate = meetingDate;
        this.type = type;
        this.content = content;
    }

    public Date meetingDate() {
        return meetingDate;
    }

    public String content() {
        return content;
    }

    public SprintMeetingType type() {
        return type;
    }

    public List<SprintMeetingDeveloper> joinDevelopers() {
        return joinDevelopers;
    }

    public SprintMeeting updateSprint(Sprint sprint) {
        this.sprint = sprint;
        return this;
    }

    public Sprint sprint() {
        return sprint;
    }

    public void saveOrUpdate() {
        if (isNewly()) {
            sprintRepository.saveSprintMeeting(this);
        } else {
            sprintRepository.updateSprintMeeting(this);
        }
    }

    public SprintMeeting updateType(SprintMeetingType type) {
        this.type = type;
        return this;
    }

    public SprintMeeting updateContent(String content) {
        this.content = content;
        return this;
    }

    public SprintMeeting updateMeetingDate(Date meetingDate) {
        this.meetingDate = meetingDate;
        return this;
    }
}

src/main/java/com/andaily/domain/developer/SprintMeetingDeveloper.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.user.Developer;

/**
 * Date: 13-9-23
 * A middle object.
 *
 * @author Shengzhao Li
 */
public class SprintMeetingDeveloper extends AbstractDomain {

    private SprintMeeting meeting;
    private Developer developer;

    public SprintMeetingDeveloper() {
    }

    public SprintMeetingDeveloper(Developer developer, SprintMeeting meeting) {
        this.meeting = meeting;
        this.developer = developer;
    }

    public SprintMeeting meeting() {
        return meeting;
    }

    public Developer developer() {
        return developer;
    }
}

src/main/java/com/andaily/domain/developer/SprintMeetingType.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.Language;
import com.andaily.domain.user.User;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public enum SprintMeetingType {

    DAILY_STANDING("Daily standing", "站立会议"),
    SPRINT_PLANNING("Sprint planning", "计划会议"),
    SPRINT_REVIEW("Sprint review", "评审会议"),
    RETROSPECTIVE("Retrospective", "回顾会议");

    private String label;
    private String cnLabel;

    private SprintMeetingType(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            final Language language = user.language();
            return language.isChinese() ? cnLabel : label;
        }
        return label;
    }

    public String getValue() {
        return name();
    }
}

src/main/java/com/andaily/domain/developer/SprintPriority.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-4
 *
 * @author Shengzhao Li
 */
public enum SprintPriority {

    HIGH("High", "高"),
    DEFAULT("Default", "默认"),
    LOW("Low", "低");

    private String label;
    private String cnLabel;

    private SprintPriority(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            return user.language().isChinese() ? cnLabel : label;
        }
        return label;
    }
}

src/main/java/com/andaily/domain/developer/SprintStatus.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.Language;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-3
 *
 * @author Shengzhao Li
 */
public enum SprintStatus {

    CREATED("Created", "已创建"),
    PENDING("Pending", "进行中"),
    //    ARCHIVED("Archived"),
    FINISHED("Finished", "已完成");

    private String label;
    private String cnLabel;

    private SprintStatus(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            final Language language = user.language();
            return language.isChinese() ? cnLabel : label;
        }
        return label;
    }

    public boolean isFinished() {
        return FINISHED.equals(this);
    }

    public boolean isPending() {
        return PENDING.equals(this);
    }

    public boolean isCreated() {
        return CREATED.equals(this);
    }
}

src/main/java/com/andaily/domain/developer/SprintTaskMoveRecord.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;

/**
 * Date: 13-10-9
 * <p/>
 * Record the sprint task move history.
 *
 * @author Shengzhao Li
 */
public class SprintTaskMoveRecord extends AbstractDomain {

    private Sprint fromSprint;
    private Sprint toSprint;

    private SprintTask task;

    public SprintTaskMoveRecord() {
    }


    public SprintTaskMoveRecord(Sprint fromSprint, Sprint toSprint, SprintTask task) {
        this.fromSprint = fromSprint;
        this.toSprint = toSprint;
        this.task = task;
    }

    public Sprint fromSprint() {
        return fromSprint;
    }

    public Sprint toSprint() {
        return toSprint;
    }

    public SprintTask task() {
        return task;
    }
}

src/main/java/com/andaily/domain/developer/burndown/ActualBurnDownPoint.java
package com.andaily.domain.developer.burndown;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Date: 13-9-25
 *
 * @author Shengzhao Li
 */
public class ActualBurnDownPoint extends BurnDownPoint {

    private BigDecimal actualRemainTime;

    private BigDecimal dateFinishedTime;

    public ActualBurnDownPoint() {
    }

    public ActualBurnDownPoint(Date date, BigDecimal actualRemainTime) {
        this.date = date;
        this.actualRemainTime = actualRemainTime;
    }

    public BigDecimal getActualRemainTime() {
        return actualRemainTime;
    }

    public String toString() {
        return "{" +
                "date=" + date +
                ",actualRemainTime=" + actualRemainTime +
                '}';
    }

    public BigDecimal getDateFinishedTime() {
        return dateFinishedTime;
    }

    public void setDateFinishedTime(BigDecimal dateFinishedTime) {
        this.dateFinishedTime = dateFinishedTime;
    }
}

src/main/java/com/andaily/domain/user/Language.java
package com.andaily.domain.user;

import java.util.Locale;

/**
 * @author Shengzhao Li
 */

public enum Language {

    CHINESE("中文") {
        @Override
        public Locale resolveLocale() {
            return Locale.SIMPLIFIED_CHINESE;
        }
    },
    ENGLISH("English") {
        @Override
        public Locale resolveLocale() {
            return Locale.US;
        }
    };

    private Language(String label) {
        this.label = label;
    }

    public abstract Locale resolveLocale();

    public String getValue() {
        return name();
    }

    public String getLabel() {
        return label;
    }

    private String label;


    public boolean isChinese() {
        return CHINESE.equals(this);
    }
}

src/main/webapp/WEB-INF/jsp/developer/project/project_form.jsp
<%--
  User: Shengzhao Li
  Date: 13-10-21
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
<head>
    <title><spring:message code="project.form.page.title" text="Project"/></title>

    <link href="${contextPath}/js/web/bootstrap/datepicker/datepicker.css" rel="stylesheet"/>
    <script src="${contextPath}/js/web/bootstrap/datepicker/bootstrap-datepicker.js"></script>
    <script src="${contextPath}/js/web/bootstrap/datepicker/bootstrap-datepicker.zh-CN.js"></script>

    <script src="${contextPath}/js/web/ckeditor/ckeditor.js"></script>
</head>
<body>
<div class="row">
    <hr/>
</div>
<form:form commandName="projectFormDto" id="projectForm">
    <form:hidden path="guid"/>
    <div class="row sprint-form">
        <div class="span8 well">
            <fieldset>
                <legend><spring:message code="project.form.page.title" text="Project"/></legend>
                <table class="width100">
                    <tr>
                        <td>
                            <label for="name"><spring:message code="project.form.page.project.name" text="Project name"/></label>
                            <spring:message code="project.form.page.project.name.placeholder" text="Project name" var="projectNameHolderMessage"/>
                            <form:input path="name" id="name" placeholder="${projectNameHolderMessage}" required="true"
                                        cssClass="span4" maxlength="255"/>
                            <form:errors path="name" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="project.form.page.project.name.help" text="Project name is required, max length: 255."/></span>
                        </td>
                        <td>
                            <label for="code"><spring:message code="project.form.page.project.code" text="Project code"/></label>
                            <spring:message code="project.form.page.project.code.holder" text="Project code" var="projectCodeHolderMessage"/>
                            <form:input path="code" id="code" placeholder="${projectCodeHolderMessage}" maxlength="255"
                                        cssClass="span2"/>
                            <form:errors path="code" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="project.form.page.project.code.help" text="A code of the project (optional)."/></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="finishDate"><spring:message code="project.form.page.finish.date" text="Finish date"/></label>

                            <div class="input-append date" id="finishDate">
                                <spring:message code="project.form.page.finish.date.holder" text="Finish date" var="finishDateHolderMessage"/>
                                <form:input path="finishDate" placeholder="${finishDateHolderMessage}" cssClass="span2"/>
                                <span class="add-on"><i class="icon-th"></i></span>
                            </div>
                            <form:errors path="finishDate" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="project.form.page.finish.date.help" text="Specify the project finish date (optional)."/></span>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <label for="description"><spring:message code="project.form.page.description" text="Description"/></label>
                            <form:textarea path="description" cssClass="ckeditor" id="description"/>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </div>
        <div class="span3 well">
            <fieldset>
                <legend><spring:message code="project.form.page.product.owner" text="Product Owner"/></legend>
                <ul class="unstyled">
                    <c:if test="${empty projectFormDto.availableProductOwners}">
                        <li><span class="text-warning"><spring:message code="project.form.page.not.available.product.owner"
                                                                       text="Not available product owners."/></span></li>
                    </c:if>
                    <c:forEach items="${projectFormDto.availableProductOwners}" var="po" varStatus="s">
                        <li>
                            <form:checkbox path="productOwnerGuids" value="${po.guid}"/> ${po.showName}
                        </li>

                        <%--For validation failed--%>
                        <form:hidden path="availableProductOwners[${s.index}].guid"/>
                        <form:hidden path="availableProductOwners[${s.index}].nickName"/>
                        <form:hidden path="availableProductOwners[${s.index}].email"/>
                    </c:forEach>
                </ul>
                <form:errors path="productOwnerGuids" cssClass="label label-warning"/>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class="span5 offset2">
            <button type="submit" class="btn btn-success btn-large"><i class="icon-plus icon-white"></i>
                <spring:message code="project.form.page.save" text="Save"/>
            </button>
            <a href="../project_/overview" class="btn btn-link"><spring:message code="project.form.page.cancel" text="Cancel"/></a>
        </div>
    </div>
</form:form>
<script type="text/javascript">
    $(function () {
        new ProjectForm('${SPRING_SECURITY_CONTEXT.authentication.principal.language.chinese?'zh-CN':'en'}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/developer/project/project_overview.jsp
<%--
  User: Shengzhao Li
  Date: 13-10-20
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="custom" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="displaytag" uri="http://displaytag.sf.net" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
<head>
    <title><spring:message code="project.overview.page.title" text="Project"/></title>
</head>
<body>
<div class="row">
    <hr/>
    <div class="span8">
        <form action="" id="projectForm" class="form-inline">
            <spring:message code="project.overview.page.form.project.name" text="Project name" var="projectNameMessage"/>
            <input type="text" name="name" value="${projectOverviewDto.name}" placeholder="${projectNameMessage}"/>
            <c:if test="${projectOverviewDto.showTeamCondition}">
                <select name="teamGuid" class="input-medium">
                    <option value=""><spring:message code="project.overview.page.form.all.teams" text="All Teams"/></option>
                    <c:forEach items="${projectOverviewDto.teamDtos}" var="t">
                        <option value="${t.guid}" ${t.guid eq projectOverviewDto.teamGuid?'selected':''}>${t.name}</option>
                    </c:forEach>
                </select>
            </c:if>
            <c:if test="${projectOverviewDto.showProductOwnerCondition}">
                <select name="productOwnerGuid" class="input-medium">
                    <option value=""><spring:message code="project.overview.page.form.all.product.owners" text="All Product Owners"/></option>
                    <c:forEach items="${projectOverviewDto.productOwners}" var="t">
                        <option value="${t.guid}" ${t.guid eq projectOverviewDto.productOwnerGuid?'selected':''}>${t.showName}</option>
                    </c:forEach>
                </select>
            </c:if>

            <button class="btn btn-default" type="submit"><i class="icon-search"></i> <spring:message code="project.overview.page.form.search" text="Search"/></button>
        </form>
    </div>
    <div class="span2">
        <span class="muted">
            <spring:message code="project.overview.page.size.projects" text="Size of projects"/>: <strong>${projectOverviewDto.totalSize}</strong>
        </span>
    </div>
    <div class="span2">
        <sec:authorize ifAnyGranted="ROLE_SUPER_MAN,ROLE_PRODUCT_OWNER">
            <a class="btn btn-success btn-small" href="../project_form/create"><i
                    class="icon-plus icon-white"></i> <spring:message code="project.overview.page.create.project" text="Create project"/></a>
        </sec:authorize>
    </div>

</div>
<div class="row">
    <div class="span12">
        <div class="alert alert-success hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="icon-ok-sign icon-white"></i>
                <span id="projectFormSuccess" class="hide"><spring:message code="project.overview.page.alert.add.edit.success" text="Add/Edit the project successful!"/></span>
            </div>
        </div>
        <div class="alert alert-info hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="icon-info-sign icon-white"></i>
                <span id="archiveProjectInfo" class="hide"><spring:message code="project.overview.page.alert.archive.finished" text="Archive the project already finished!"/></span>
            </div>
        </div>
        <div class="alert alert-error hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="icon-warning-sign icon-white"></i>
                <%--<span id="alertErrorInfo"></span>--%>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="span12">
        <spring:message code="project.overview.page.table.name" text="Name" var="nameMessage"/>
        <spring:message code="project.overview.page.table.code" text="Code" var="codeMessage"/>
        <spring:message code="project.overview.page.table.finish.date" text="Finish date" var="finishDateMessage"/>
        <spring:message code="project.overview.page.table.product.owner" text="Product owner" var="productOwnerMessage"/>
        <spring:message code="project.overview.page.table.team" text="Team" var="teamMessage"/>

        <displaytag:table list="${projectOverviewDto}" class="table table-hover table-striped" id="project"
                          form="projectForm">
            <displaytag:column title="${nameMessage}" headerClass="width40">
                <div class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            ${project.name}
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <custom:project_overview_menus project="${project}"/>
                    </ul>
                </div>
            </displaytag:column>
            <displaytag:column title="${codeMessage}" property="code" style="vertical-align: middle;"/>
            <displaytag:column title="${finishDateMessage}" property="finishDateAsText" style="vertical-align: middle;"
                               class="text-success"/>
            <displaytag:column title="${productOwnerMessage}" property="productOwnersAsText" style="vertical-align: middle;"/>
            <displaytag:column title="${teamMessage}" property="teamsAsText" style="vertical-align: middle;"/>
            <%--<displaytag:column title="Create time" property="createTime" style="vertical-align: middle;"/>--%>
            <displaytag:column title="&nbsp;" style="vertical-align: middle;">
                <a href="javascript:void(0)" data-content="${project.htmlTip}" class="projectDetails"><i
                        class="icon-info-sign"></i></a>
            </displaytag:column>
        </displaytag:table>
    </div>
</div>

<%--JS i18n messages--%>
<div class="hidden">
    <span id="projectDescMessage"><spring:message code="project.overview.page.js.project.description"
                                                  text="Project description"/></span>
</div>
<script type="text/javascript">
    $(function () {
        new ProjectOverview('${param.alert}');
    });
</script>
</body>
</html>