src/main/java/com/andaily/domain/AbstractDomain.java
package com.andaily.domain;

import com.andaily.domain.shared.DateUtils;
import com.andaily.domain.shared.GuidGenerator;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Shengzhao Li
 */
public abstract class AbstractDomain implements Serializable {

    /**
     * Database id
     */
    protected int id;

    protected boolean archived;
    /**
     * Domain business guid.
     */
    protected String guid = GuidGenerator.generate();

    /**
     * The domain create time.
     */
    protected Date createTime = DateUtils.now();

    public AbstractDomain() {
    }

    public int id() {
        return id;
    }

    public void id(int id) {
        this.id = id;
    }

    public boolean archived() {
        return archived;
    }

    public AbstractDomain archived(boolean archived) {
        this.archived = archived;
        return this;
    }

    public String guid() {
        return guid;
    }

    public void guid(String guid) {
        this.guid = guid;
    }

    public Date createTime() {
        return createTime;
    }

    public boolean isNewly() {
        return id == 0;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof AbstractDomain)) {
            return false;
        }
        AbstractDomain that = (AbstractDomain) o;
        return guid.equals(that.guid);
    }

    @Override
    public int hashCode() {
        return guid.hashCode();
    }

    //For subclass override it
    public void saveOrUpdate() {
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).
                append("id", id).
                append("archived", archived).
                append("guid", guid).
                append("createTime", createTime).
                toString();
    }
}

src/main/java/com/andaily/domain/developer/Backlog.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.developer.operation.ScrumSecurityChecker;
import com.andaily.domain.developer.project.Project;
import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.User;
import com.andaily.infrastructure.support.LogHelper;
import com.andaily.web.context.BeanProvider;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Date: 13-8-3
 *
 * @author Shengzhao Li
 */
public class Backlog extends AbstractDomain {

    private static LogHelper log = LogHelper.create(Backlog.class);
    private transient BacklogRepository backlogRepository = BeanProvider.getBean(BacklogRepository.class);
    private transient SprintRepository sprintRepository = BeanProvider.getBean(SprintRepository.class);

    private SprintPriority priority = SprintPriority.DEFAULT;

    private String content;

    //backlog number, unique
    private int number;

    private BacklogType type = BacklogType.NEEDS;

    //If the backlog do not refer an exist sprint, the value is null
    private Sprint sprint;

    private User creator;

    // update the field value when create Sprint
    private User joinSprintUser;
    private Date joinSprintTime;

    // The field max hours is 16
    //Unit: hour
    private int estimateTime;

    private Project project;

    //documents
    private List<BacklogDocument> documents = new ArrayList<>();

    public Backlog() {
    }

    public Backlog(SprintPriority priority, String content, BacklogType type) {
        this.priority = priority;
        this.content = content;
        this.type = type;
    }

    public int number() {
        return number;
    }

    public Backlog number(int number) {
        this.number = number;
        return this;
    }

    public Backlog updateCreator(User creator) {
        this.creator = creator;
        return this;
    }

    public SprintPriority priority() {
        return priority;
    }

    public String content() {
        return content;
    }

    public BacklogType type() {
        return type;
    }

    public Sprint sprint() {
        return sprint;
    }

    public User creator() {
        return creator;
    }

    public User joinSprintUser() {
        return joinSprintUser;
    }

    public Date joinSprintTime() {
        return joinSprintTime;
    }

    public Backlog updateContent(String content) {
        this.content = content;
        return this;
    }

    public Backlog updateJoinSprintTime(Date joinSprintTime) {
        this.joinSprintTime = joinSprintTime;
        return this;
    }

    public Backlog updateSprint(Sprint sprint) {
        this.sprint = sprint;
        return this;
    }

    public Backlog updateType(BacklogType type) {
        this.type = type;
        return this;
    }

    public Backlog updatePriority(SprintPriority priority) {
        this.priority = priority;
        return this;
    }

    public void saveOrUpdate() {
        if (isNewly()) {
            backlogRepository.saveBacklog(this);
        } else {
            backlogRepository.updateBacklog(this);
        }
    }

    public Backlog archive() {
        ScrumSecurityChecker.checkBacklogReferSprint(this, false);
        this.archived(true);
        log.debug(SecurityUtils.currUser().displayName() + " archive the backlog [" + this.guid + "]");
        return this;
    }

    @Override
    public String toString() {
        return "{" +
                "id='" + id() + '\'' +
                ",content='" + content + '\'' +
                '}';
    }

    public int estimateTime() {
        return estimateTime;
    }

    public Backlog updateEstimateTime(int estimateTime) {
        this.estimateTime = estimateTime;
        return this;
    }

    public Project project() {
        return project;
    }

    public Backlog updateProject(Project project) {
        this.project = project;
        return this;
    }

    public List<BacklogDocument> documents() {
        return documents;
    }

    /**
     * Amount of the task refer the backlog
     *
     * @return Amount of task
     */
    public int referencedSprintTasks() {
        return sprintRepository.totalSprintTasksOfBacklog(this);
    }
}

src/main/java/com/andaily/domain/developer/BacklogDocument.java
package com.andaily.domain.developer;

import com.andaily.domain.developer.commons.Document;
import com.andaily.domain.developer.commons.GeckoFile;

/**
 * @author Shengzhao Li
 */
public class BacklogDocument extends Document {

    private Backlog backlog;

    public BacklogDocument() {
    }

    public BacklogDocument(Backlog backlog, GeckoFile file) {
        super(file);
        this.backlog = backlog;
    }

    @Override
    public void saveOrUpdate() {
        if (isNewly()) {
            file.saveOrUpdate();
            file = commonsRepository.findGeckoFileByGuid(file.guid());
            commonsRepository.saveBacklogDocument(this);
        } else {
            throw new UnsupportedOperationException("Update BacklogDocument is un-supported");
        }
    }

    public Backlog backlog() {
        return backlog;
    }
}

src/main/java/com/andaily/domain/developer/BacklogRepository.java
package com.andaily.domain.developer;

import com.andaily.domain.developer.project.Project;
import com.andaily.domain.shared.Repository;
import com.andaily.domain.user.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * Date: 13-8-5
 *
 * @author Shengzhao Li
 */
public interface BacklogRepository extends Repository {

    Backlog findByGuid(String guid);

    void saveBacklog(Backlog backlog);

    void updateBacklog(Backlog backlog);

    List<Backlog> findAvailableBacklogs(String projectGuid);

    void updateSprintBacklogs(@Param("sprintGuid") String sprintGuid, @Param("backlogGuids") List<String> backlogGuids, @Param("user") User user);

    void cleanBacklogsSprint(@Param("backlogs") List<Backlog> backlogs);

    List<Backlog> findSprintBacklogs(String sprintGuid);

    List<Backlog> findOverviewBacklogs(Map<String, Object> map);

    int totalOverviewBacklogs(Map<String, Object> map);

    List<Backlog> findUnusedBacklogsByProject(Project project);

    int maxBacklogNumber();
}

src/main/java/com/andaily/domain/developer/BacklogType.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-5
 *
 * @author Shengzhao Li
 */
public enum BacklogType {

    NEEDS("Needs", "需求"),
    BUGS("Bug", "Bug"),
    SUGGESTIONS("Suggestions", "建议");

    private String label;
    private String cnLabel;

    private BacklogType(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            return user.language().isChinese() ? cnLabel : label;
        }
        return label;
    }
}

src/main/java/com/andaily/domain/developer/ScrumComment.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.user.Developer;

import java.util.Date;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public class ScrumComment extends AbstractDomain {

    //who
    private Developer developer;
    //when
    private Date commentTime;
    //do what
    private String content;

    public ScrumComment() {
    }

    public ScrumComment(Developer developer, Date commentTime, String content) {
        this.developer = developer;
        this.commentTime = commentTime;
        this.content = content;
    }

    public Developer developer() {
        return developer;
    }

    public Date commentTime() {
        return commentTime;
    }

    public String content() {
        return content;
    }
}

src/main/java/com/andaily/domain/developer/ScrumRepository.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.Repository;

/**
 * Date: 13-9-23
 *
 * @author Shengzhao Li
 */
public interface ScrumRepository extends Repository {

    void saveComment(ScrumComment comment);

    ScrumComment findCommentByGuid(String guid);
}

src/main/java/com/andaily/domain/developer/SprintMeeting.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.web.context.BeanProvider;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public class SprintMeeting extends AbstractDomain {

    private transient SprintRepository sprintRepository = BeanProvider.getBean(SprintRepository.class);

    private Date meetingDate;
    private String content;

    private SprintMeetingType type;

    //The developers which join the meeting
    private List<SprintMeetingDeveloper> joinDevelopers = new ArrayList<SprintMeetingDeveloper>();

    private Sprint sprint;

    public SprintMeeting() {
    }

    public SprintMeeting(Date meetingDate, SprintMeetingType type, String content) {
        this.meetingDate = meetingDate;
        this.type = type;
        this.content = content;
    }

    public Date meetingDate() {
        return meetingDate;
    }

    public String content() {
        return content;
    }

    public SprintMeetingType type() {
        return type;
    }

    public List<SprintMeetingDeveloper> joinDevelopers() {
        return joinDevelopers;
    }

    public SprintMeeting updateSprint(Sprint sprint) {
        this.sprint = sprint;
        return this;
    }

    public Sprint sprint() {
        return sprint;
    }

    public void saveOrUpdate() {
        if (isNewly()) {
            sprintRepository.saveSprintMeeting(this);
        } else {
            sprintRepository.updateSprintMeeting(this);
        }
    }

    public SprintMeeting updateType(SprintMeetingType type) {
        this.type = type;
        return this;
    }

    public SprintMeeting updateContent(String content) {
        this.content = content;
        return this;
    }

    public SprintMeeting updateMeetingDate(Date meetingDate) {
        this.meetingDate = meetingDate;
        return this;
    }
}

src/main/java/com/andaily/domain/developer/SprintMeetingDeveloper.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.user.Developer;

/**
 * Date: 13-9-23
 * A middle object.
 *
 * @author Shengzhao Li
 */
public class SprintMeetingDeveloper extends AbstractDomain {

    private SprintMeeting meeting;
    private Developer developer;

    public SprintMeetingDeveloper() {
    }

    public SprintMeetingDeveloper(Developer developer, SprintMeeting meeting) {
        this.meeting = meeting;
        this.developer = developer;
    }

    public SprintMeeting meeting() {
        return meeting;
    }

    public Developer developer() {
        return developer;
    }
}

src/main/java/com/andaily/domain/developer/SprintMeetingType.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.Language;
import com.andaily.domain.user.User;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public enum SprintMeetingType {

    DAILY_STANDING("Daily standing", "站立会议"),
    SPRINT_PLANNING("Sprint planning", "计划会议"),
    SPRINT_REVIEW("Sprint review", "评审会议"),
    RETROSPECTIVE("Retrospective", "回顾会议");

    private String label;
    private String cnLabel;

    private SprintMeetingType(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            final Language language = user.language();
            return language.isChinese() ? cnLabel : label;
        }
        return label;
    }

    public String getValue() {
        return name();
    }
}

src/main/java/com/andaily/domain/developer/burndown/BurnDown.java
package com.andaily.domain.developer.burndown;

import com.andaily.domain.developer.Sprint;
import com.andaily.domain.developer.operation.SprintTimeUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Date: 13-9-24
 * <p/>
 * Define a sprint burn down
 *
 * @author Shengzhao Li
 */
public class BurnDown implements Serializable {

    private String sprintGuid;
    private String sprintName;

    //unit: minute
    private int estimateTimes;
    //unit minute
    private int usedTimes;

    private List<BurnDownLabel> labels = new ArrayList<BurnDownLabel>();

    private List<ExpectBurnDownPoint> expectPoints = new ArrayList<ExpectBurnDownPoint>();
    private List<ActualBurnDownPoint> actualPoints = new ArrayList<ActualBurnDownPoint>();

    public BurnDown() {
    }

    /**
     * Should be call {@link BurnDownGenerator} to generate <code>BurnDown</code> instance.
     *
     * @param sprint Sprint
     */
    public BurnDown(Sprint sprint) {
        this.sprintGuid = sprint.guid();
        this.sprintName = sprint.name();

        this.usedTimes = sprint.usedTimes();
        this.estimateTimes = sprint.estimateTimes();
    }

    public String getSprintGuid() {
        return sprintGuid;
    }

    public String getSprintName() {
        return sprintName;
    }

    public int getEstimateTimes() {
        return estimateTimes;
    }

    public String getEstimateTimesAsHours() {
        return SprintTimeUtils.taskTimeAsString(estimateTimes);
    }


    public int getUsedTimes() {
        return usedTimes;
    }

    public String getUsedTimesAsHours() {
        return SprintTimeUtils.taskTimeAsString(usedTimes);
    }


    public List<ExpectBurnDownPoint> getExpectPoints() {
        return expectPoints;
    }

    public List<ActualBurnDownPoint> getActualPoints() {
        return actualPoints;
    }

    public BurnDown setExpectPoints(List<ExpectBurnDownPoint> expectPoints) {
        this.expectPoints = expectPoints;
        return this;
    }

    public BurnDown setActualPoints(List<ActualBurnDownPoint> actualPoints) {
        this.actualPoints = actualPoints;
        return this;
    }

    public List<BurnDownLabel> getLabels() {
        return labels;
    }

    public void setLabels(List<BurnDownLabel> labels) {
        this.labels = labels;
    }

    @Override
    public String toString() {
        return "{" +
                "usedTimes=" + usedTimes +
                ", estimateTimes=" + estimateTimes +
                ", sprintName='" + sprintName + '\'' +
                ", sprintGuid='" + sprintGuid + '\'' +
                '}';
    }
}

src/main/webapp/WEB-INF/jsp/developer/assign_task_form.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<div class="well well-small">
    <div style="margin-left: 20px;">
        <p class="text-info">
            <spring:message code="assign.task.form.page.first" text="Assign the task(\#{0}) to" arguments="${assignTaskDto.taskNumber}"/>
        </p>
        <select id="executorFormSelect">
            <option value=""><spring:message code="assign.task.form.page.select.developer" text="--Select a developer--" /></option>
            <c:forEach items="${assignTaskDto.developers}" var="d">
                <option value="${d.guid}" ${(d.guid eq assignTaskDto.executorGuid)?'selected':''}>${d.showName}</option>
            </c:forEach>
        </select>
        <span class="label label-warning hidden" id="assignTaskErrorInfo"><spring:message code="assign.task.form.page.select.developer.help" text="Please select a developer firstly." /></span>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/developer/backlog_form.jsp
<%--
  User: Shengzhao Li
  Date: 13-9-8
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<html>
<head>
    <title><spring:message code="backlog.form.page.title" text="Backlog"/></title>
    <script src="${contextPath}/js/web/ckeditor/ckeditor.js"></script>
</head>
<body>
<div class="row">
    <hr/>
    <div class="span12">
        <div class="alert alert-success hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="icon-ok-sign icon-white"></i>
                <%--<span id="successful" class="hide">Add/Edit the sprint successful!</span>--%>
            </div>
        </div>
        <div class="alert alert-info hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="icon-info-sign icon-white"></i>
                <span id="successAddNext" class="hide"><spring:message code="backlog.form.page.alert.save.finished" text="Save the backlog finished, please add new one."/></span>
            </div>
        </div>
        <div class="alert alert-error hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="icon-warning-sign icon-white"></i>
                <%--<span id="alertErrorInfo"></span>--%>
            </div>
        </div>
    </div>
</div>
<form:form commandName="backlogFormDto" id="backlogForm" enctype="multipart/form-data">
    <form:hidden path="guid"/>
    <div class="row backlog-form">
        <div class="span8 well">
            <fieldset>
                <legend><spring:message code="backlog.form.page.title" text="Backlog"/></legend>
                <table class="width100">
                    <tr>
                        <td>
                            <label><spring:message code="backlog.form.page.form.type" text="Type"/></label>
                            <c:forEach items="${backlogFormDto.availableTypes}" var="p">
                                <label class="radio inline">
                                    <form:radiobutton path="type" value="${p.value}"/> ${p.label}
                                </label>
                            </c:forEach>
                            <form:errors path="type" cssClass="label label-warning"/>
                            <span class="help-block">&nbsp;</span>
                        </td>
                        <td>
                            <label><spring:message code="backlog.form.page.form.priority" text="Priority"/></label>
                            <c:forEach items="${backlogFormDto.availablePriorities}" var="p">
                                <label class="radio inline">
                                    <form:radiobutton path="priority" value="${p.value}"/> ${p.label}
                                </label>
                            </c:forEach>
                            <form:errors path="priority" cssClass="label label-warning"/>
                            <span class="help-block">&nbsp;</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="estimateTime"><spring:message code="backlog.form.page.form.estimate" text="Estimate time(hour)"/></label>
                            <input type="number" name="estimateTime" id="estimateTime"
                                   placeholder="Estimate of the backlog"
                                   required="true" value="${backlogFormDto.estimateTime}"/>
                            <form:errors path="estimateTime" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="backlog.form.page.form.estimate.help" text="Suggest the estimate do not more than 16 hours"/></span>
                        </td>
                        <td>
                            <label for="projectGuid"><spring:message code="backlog.form.page.form.project" text="Project"/></label>

                            <spring:message code="backlog.form.page.form.project.choose" text="Choose a project" var="chooseProjectMessage"/>
                            <c:if test="${backlogFormDto.newly}" var="newly">
                                <form:select path="projectGuid" id="projectGuid">
                                    <%--disabled="${ empty backlogFormDto.projectGuid?'false':'true'}"--%>
                                    <form:option value="" label="${chooseProjectMessage}"/>
                                    <form:options items="${backlogFormDto.availableProjects}" itemLabel="name"
                                                  itemValue="guid"/>
                                </form:select>
                            </c:if>
                            <c:if test="${not newly}">
                                <form:select path="projectGuid" id="projectGuid">
                                    <form:options items="${backlogFormDto.availableProjects}" itemLabel="name"
                                                  itemValue="guid"/>
                                </form:select>
                            </c:if>
                            <form:errors path="projectGuid" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="backlog.form.page.form.project.help" text="Specify a project"/></span>

                                <%--For bind list data if validation failed--%>
                            <c:forEach items="${backlogFormDto.availableProjects}" var="p" varStatus="s">
                                <input type="hidden" name="availableProjects[${s.index}].guid" value="${p.guid}"/>
                                <input type="hidden" name="availableProjects[${s.index}].name" value="${p.name}"/>
                            </c:forEach>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <label for="content"><spring:message code="backlog.form.page.form.content" text="Content"/> <form:errors path="content"
                                                                      cssClass="label label-warning"/></label>
                            <form:textarea path="content" cssClass="ckeditor" id="content"/>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </div>
        <div class="span3 well">
            <fieldset>
                <legend><spring:message code="backlog.form.page.form.documents" text="Documents"/></legend>
            </fieldset>
            <p>
                <input type="file" name="file1"/>
            </p>

            <p>
                <input type="file" name="file2"/>
            </p>

            <p>
                <input type="file" name="file3"/>
            </p>

            <p>
                <span class="help-block"><spring:message code="backlog.form.page.form.documents.help" text="Documents of the backlog(optional), max upload  3 files."/></span>
            </p>

            <div>
                <ul class="unstyled">
                    <spring:message code="backlog.form.page.form.document.remove.confirm" text="Confirm remove" var="removeConfirmMessage"/>

                    <c:forEach items="${backlogFormDto.documentDtos}" var="d">
                        <li>
                            <a href="../file/download/${d.fileDto.guid}">${d.fileDto.name}</a>
                            <span class="muted">(${d.fileDto.sizeAsText})</span>
                            <spring:message code="backlog.form.page.form.document.remove.content" text="Are you sure remove the document({0}) ?"
                                            arguments="${d.fileDto.name}" var="removeContentMessage"/>
                            <a href="../backlog_action/remove_document/${d.guid}?backlogGuid=${backlogFormDto.guid}"
                               confirm-title="${removeConfirmMessage}"
                               confirm-content="${removeContentMessage}"
                               class="confirm">
                                <i class="icon-remove"></i></a>
                        </li>
                    </c:forEach>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span5 offset2">
            <form:hidden path="addNext" id="addNext"/>
            <button type="submit" class="btn btn-success btn-large" addNext="false"><i class="icon-plus icon-white"></i>
                <spring:message code="backlog.form.page.form.save" text="Save"/>
            </button>
            <button type="submit" class="btn btn-info btn-large" addNext="true"><i class="icon-plus icon-white"></i>
                <spring:message code="backlog.form.page.form.save.next" text="Save & Add next"/>
            </button>
            <a href="../backlog_overview?projectGuid=${backlogFormDto.projectGuid}" class="btn btn-link"><spring:message
                    code="backlog.form.page.form.cancel" text="Cancel"/></a>
        </div>
    </div>
</form:form>
<script type="text/javascript">
    $(function () {
        new BacklogForm('${param.alert}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/developer/burndown_details.jsp
<%--
  User: Shengzhao Li
  Date: 13-9-29
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<div>
    <div>
        <canvas id="burnDownDetailsChart"></canvas>
    </div>
    <div class="alert alert-info text-center">
        <spring:message code="burndown.details.page.estimate" text="Estimate"/>: <strong>${burnDownDetailsDto.burnDownWrapper.burnDown.estimateTimesAsHours}</strong>
        &nbsp;&nbsp;&nbsp;
        <spring:message code="burndown.details.page.used" text="Used"/>: <strong>${burnDownDetailsDto.burnDownWrapper.burnDown.usedTimesAsHours}</strong>
    </div>
    <script type="text/javascript">
        var labels = [];
        var expectDatas = [];
        var actualDatas = [];

        <c:forEach items="${burnDownDetailsDto.burnDownWrapper.burnDown.labels}" var="label">
        labels.push('${label.dateAsDay}');
        </c:forEach>
        <c:forEach items="${burnDownDetailsDto.burnDownWrapper.burnDown.expectPoints}" var="exp">
        expectDatas.push('${exp.expectRemainTime}');
        </c:forEach>
        <c:forEach items="${burnDownDetailsDto.burnDownWrapper.burnDown.actualPoints}" var="actual">
        actualDatas.push('${actual.actualRemainTime}');
        </c:forEach>

        var data = {
            labels:labels,
            datasets:[
                {
                    fillColor:"rgba(255,255,255,0.5)",
                    strokeColor:"rgba(0,0,255,0.8)",
                    pointColor:"rgba(0,0,255,0.8)",
                    pointStrokeColor:"#fff",
                    data:expectDatas
                },
                {
                    fillColor:"rgba(151,187,205,0.4)",
                    strokeColor:"rgba(255,0,0,0.8)",
                    pointColor:"rgba(255,0,0,0.8)",
                    pointStrokeColor:"#fff",
                    data:actualDatas
                }
            ]
        };

        $("#burnDownDetailsChart").attr("height", 200).attr("width", 520);
        var context = $("#burnDownDetailsChart").get(0).getContext("2d");
        new Chart(context).Line(data, {
            scaleOverride:true,
            scaleStepWidth:${burnDownDetailsDto.burnDownWrapper.chartStepWidth},
            scaleStartValue:0,
            scaleSteps:${burnDownDetailsDto.burnDownWrapper.chartSteps}
        });
    </script>
</div>