src/main/java/com/andaily/domain/developer/Backlog.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.developer.operation.ScrumSecurityChecker;
import com.andaily.domain.developer.project.Project;
import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.User;
import com.andaily.infrastructure.support.LogHelper;
import com.andaily.web.context.BeanProvider;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Date: 13-8-3
 *
 * @author Shengzhao Li
 */
public class Backlog extends AbstractDomain {

    private static LogHelper log = LogHelper.create(Backlog.class);
    private transient BacklogRepository backlogRepository = BeanProvider.getBean(BacklogRepository.class);
    private transient SprintRepository sprintRepository = BeanProvider.getBean(SprintRepository.class);

    private SprintPriority priority = SprintPriority.DEFAULT;

    private String content;

    //backlog number, unique
    private int number;

    private BacklogType type = BacklogType.NEEDS;

    //If the backlog do not refer an exist sprint, the value is null
    private Sprint sprint;

    private User creator;

    // update the field value when create Sprint
    private User joinSprintUser;
    private Date joinSprintTime;

    // The field max hours is 16
    //Unit: hour
    private int estimateTime;

    private Project project;

    //documents
    private List<BacklogDocument> documents = new ArrayList<>();

    public Backlog() {
    }

    public Backlog(SprintPriority priority, String content, BacklogType type) {
        this.priority = priority;
        this.content = content;
        this.type = type;
    }

    public int number() {
        return number;
    }

    public Backlog number(int number) {
        this.number = number;
        return this;
    }

    public Backlog updateCreator(User creator) {
        this.creator = creator;
        return this;
    }

    public SprintPriority priority() {
        return priority;
    }

    public String content() {
        return content;
    }

    public BacklogType type() {
        return type;
    }

    public Sprint sprint() {
        return sprint;
    }

    public User creator() {
        return creator;
    }

    public User joinSprintUser() {
        return joinSprintUser;
    }

    public Date joinSprintTime() {
        return joinSprintTime;
    }

    public Backlog updateContent(String content) {
        this.content = content;
        return this;
    }

    public Backlog updateJoinSprintTime(Date joinSprintTime) {
        this.joinSprintTime = joinSprintTime;
        return this;
    }

    public Backlog updateSprint(Sprint sprint) {
        this.sprint = sprint;
        return this;
    }

    public Backlog updateType(BacklogType type) {
        this.type = type;
        return this;
    }

    public Backlog updatePriority(SprintPriority priority) {
        this.priority = priority;
        return this;
    }

    public void saveOrUpdate() {
        if (isNewly()) {
            backlogRepository.saveBacklog(this);
        } else {
            backlogRepository.updateBacklog(this);
        }
    }

    public Backlog archive() {
        ScrumSecurityChecker.checkBacklogReferSprint(this, false);
        this.archived(true);
        log.debug(SecurityUtils.currUser().displayName() + " archive the backlog [" + this.guid + "]");
        return this;
    }

    @Override
    public String toString() {
        return "{" +
                "id='" + id() + '\'' +
                ",content='" + content + '\'' +
                '}';
    }

    public int estimateTime() {
        return estimateTime;
    }

    public Backlog updateEstimateTime(int estimateTime) {
        this.estimateTime = estimateTime;
        return this;
    }

    public Project project() {
        return project;
    }

    public Backlog updateProject(Project project) {
        this.project = project;
        return this;
    }

    public List<BacklogDocument> documents() {
        return documents;
    }

    /**
     * Amount of the task refer the backlog
     *
     * @return Amount of task
     */
    public int referencedSprintTasks() {
        return sprintRepository.totalSprintTasksOfBacklog(this);
    }
}

src/main/java/com/andaily/domain/developer/BacklogDocument.java
package com.andaily.domain.developer;

import com.andaily.domain.developer.commons.Document;
import com.andaily.domain.developer.commons.GeckoFile;

/**
 * @author Shengzhao Li
 */
public class BacklogDocument extends Document {

    private Backlog backlog;

    public BacklogDocument() {
    }

    public BacklogDocument(Backlog backlog, GeckoFile file) {
        super(file);
        this.backlog = backlog;
    }

    @Override
    public void saveOrUpdate() {
        if (isNewly()) {
            file.saveOrUpdate();
            file = commonsRepository.findGeckoFileByGuid(file.guid());
            commonsRepository.saveBacklogDocument(this);
        } else {
            throw new UnsupportedOperationException("Update BacklogDocument is un-supported");
        }
    }

    public Backlog backlog() {
        return backlog;
    }
}

src/main/java/com/andaily/domain/developer/BacklogRepository.java
package com.andaily.domain.developer;

import com.andaily.domain.developer.project.Project;
import com.andaily.domain.shared.Repository;
import com.andaily.domain.user.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * Date: 13-8-5
 *
 * @author Shengzhao Li
 */
public interface BacklogRepository extends Repository {

    Backlog findByGuid(String guid);

    void saveBacklog(Backlog backlog);

    void updateBacklog(Backlog backlog);

    List<Backlog> findAvailableBacklogs(String projectGuid);

    void updateSprintBacklogs(@Param("sprintGuid") String sprintGuid, @Param("backlogGuids") List<String> backlogGuids, @Param("user") User user);

    void cleanBacklogsSprint(@Param("backlogs") List<Backlog> backlogs);

    List<Backlog> findSprintBacklogs(String sprintGuid);

    List<Backlog> findOverviewBacklogs(Map<String, Object> map);

    int totalOverviewBacklogs(Map<String, Object> map);

    List<Backlog> findUnusedBacklogsByProject(Project project);

    int maxBacklogNumber();
}

src/main/java/com/andaily/domain/developer/BacklogType.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-5
 *
 * @author Shengzhao Li
 */
public enum BacklogType {

    NEEDS("Needs", "需求"),
    BUGS("Bug", "Bug"),
    SUGGESTIONS("Suggestions", "建议");

    private String label;
    private String cnLabel;

    private BacklogType(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            return user.language().isChinese() ? cnLabel : label;
        }
        return label;
    }
}

src/main/java/com/andaily/domain/developer/ScrumComment.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.user.Developer;

import java.util.Date;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public class ScrumComment extends AbstractDomain {

    //who
    private Developer developer;
    //when
    private Date commentTime;
    //do what
    private String content;

    public ScrumComment() {
    }

    public ScrumComment(Developer developer, Date commentTime, String content) {
        this.developer = developer;
        this.commentTime = commentTime;
        this.content = content;
    }

    public Developer developer() {
        return developer;
    }

    public Date commentTime() {
        return commentTime;
    }

    public String content() {
        return content;
    }
}

src/main/java/com/andaily/domain/developer/ScrumRepository.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.Repository;

/**
 * Date: 13-9-23
 *
 * @author Shengzhao Li
 */
public interface ScrumRepository extends Repository {

    void saveComment(ScrumComment comment);

    ScrumComment findCommentByGuid(String guid);
}

src/main/java/com/andaily/domain/developer/SprintMeeting.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.web.context.BeanProvider;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public class SprintMeeting extends AbstractDomain {

    private transient SprintRepository sprintRepository = BeanProvider.getBean(SprintRepository.class);

    private Date meetingDate;
    private String content;

    private SprintMeetingType type;

    //The developers which join the meeting
    private List<SprintMeetingDeveloper> joinDevelopers = new ArrayList<SprintMeetingDeveloper>();

    private Sprint sprint;

    public SprintMeeting() {
    }

    public SprintMeeting(Date meetingDate, SprintMeetingType type, String content) {
        this.meetingDate = meetingDate;
        this.type = type;
        this.content = content;
    }

    public Date meetingDate() {
        return meetingDate;
    }

    public String content() {
        return content;
    }

    public SprintMeetingType type() {
        return type;
    }

    public List<SprintMeetingDeveloper> joinDevelopers() {
        return joinDevelopers;
    }

    public SprintMeeting updateSprint(Sprint sprint) {
        this.sprint = sprint;
        return this;
    }

    public Sprint sprint() {
        return sprint;
    }

    public void saveOrUpdate() {
        if (isNewly()) {
            sprintRepository.saveSprintMeeting(this);
        } else {
            sprintRepository.updateSprintMeeting(this);
        }
    }

    public SprintMeeting updateType(SprintMeetingType type) {
        this.type = type;
        return this;
    }

    public SprintMeeting updateContent(String content) {
        this.content = content;
        return this;
    }

    public SprintMeeting updateMeetingDate(Date meetingDate) {
        this.meetingDate = meetingDate;
        return this;
    }
}

src/main/java/com/andaily/domain/developer/SprintMeetingDeveloper.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.user.Developer;

/**
 * Date: 13-9-23
 * A middle object.
 *
 * @author Shengzhao Li
 */
public class SprintMeetingDeveloper extends AbstractDomain {

    private SprintMeeting meeting;
    private Developer developer;

    public SprintMeetingDeveloper() {
    }

    public SprintMeetingDeveloper(Developer developer, SprintMeeting meeting) {
        this.meeting = meeting;
        this.developer = developer;
    }

    public SprintMeeting meeting() {
        return meeting;
    }

    public Developer developer() {
        return developer;
    }
}

src/main/java/com/andaily/domain/developer/SprintMeetingType.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.Language;
import com.andaily.domain.user.User;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public enum SprintMeetingType {

    DAILY_STANDING("Daily standing", "站立会议"),
    SPRINT_PLANNING("Sprint planning", "计划会议"),
    SPRINT_REVIEW("Sprint review", "评审会议"),
    RETROSPECTIVE("Retrospective", "回顾会议");

    private String label;
    private String cnLabel;

    private SprintMeetingType(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            final Language language = user.language();
            return language.isChinese() ? cnLabel : label;
        }
        return label;
    }

    public String getValue() {
        return name();
    }
}

src/main/java/com/andaily/domain/developer/SprintPriority.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-4
 *
 * @author Shengzhao Li
 */
public enum SprintPriority {

    HIGH("High", "高"),
    DEFAULT("Default", "默认"),
    LOW("Low", "低");

    private String label;
    private String cnLabel;

    private SprintPriority(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            return user.language().isChinese() ? cnLabel : label;
        }
        return label;
    }
}

src/main/java/com/andaily/domain/developer/SprintStatus.java
package com.andaily.domain.developer;

import com.andaily.domain.shared.security.SecurityUtils;
import com.andaily.domain.user.Developer;
import com.andaily.domain.user.Language;
import com.andaily.domain.user.User;

/**
 * Date: 13-8-3
 *
 * @author Shengzhao Li
 */
public enum SprintStatus {

    CREATED("Created", "已创建"),
    PENDING("Pending", "进行中"),
    //    ARCHIVED("Archived"),
    FINISHED("Finished", "已完成");

    private String label;
    private String cnLabel;

    private SprintStatus(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public String getValue() {
        return name();
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            final Language language = user.language();
            return language.isChinese() ? cnLabel : label;
        }
        return label;
    }

    public boolean isFinished() {
        return FINISHED.equals(this);
    }

    public boolean isPending() {
        return PENDING.equals(this);
    }

    public boolean isCreated() {
        return CREATED.equals(this);
    }
}

src/main/java/com/andaily/domain/developer/SprintTaskMoveRecord.java
package com.andaily.domain.developer;

import com.andaily.domain.AbstractDomain;

/**
 * Date: 13-10-9
 * <p/>
 * Record the sprint task move history.
 *
 * @author Shengzhao Li
 */
public class SprintTaskMoveRecord extends AbstractDomain {

    private Sprint fromSprint;
    private Sprint toSprint;

    private SprintTask task;

    public SprintTaskMoveRecord() {
    }


    public SprintTaskMoveRecord(Sprint fromSprint, Sprint toSprint, SprintTask task) {
        this.fromSprint = fromSprint;
        this.toSprint = toSprint;
        this.task = task;
    }

    public Sprint fromSprint() {
        return fromSprint;
    }

    public Sprint toSprint() {
        return toSprint;
    }

    public SprintTask task() {
        return task;
    }
}

src/main/java/com/andaily/domain/user/ScrumTerm.java
package com.andaily.domain.user;

import com.andaily.domain.shared.security.SecurityUtils;

import java.util.Arrays;
import java.util.List;

/**
 * Date: 13-9-22
 *
 * @author Shengzhao Li
 */
public enum ScrumTerm {

    SUPER_MAN("Super Man", "超级用户"),
    PRODUCT_OWNER("Product Owner", "产品负责人"),
    MASTER("Scrum Master", "Scrum Master"),
    MEMBER("Scrum Member", "Scrum Member");

    private String label;
    private String cnLabel;

    private ScrumTerm(String label, String cnLabel) {
        this.label = label;
        this.cnLabel = cnLabel;
    }

    public static List<ScrumTerm> scrumTerms() {
        return Arrays.asList(PRODUCT_OWNER, MASTER, MEMBER);
    }

    public String getLabel() {
        final User user = SecurityUtils.currUser();
        if (user != null && user instanceof Developer) {
            final Language language = user.language();
            return language.isChinese() ? cnLabel : label;
        }
        return label;
    }

    public String getValue() {
        return name();
    }

    public boolean isMaster() {
        return MASTER.equals(this);
    }

    public boolean isMember() {
        return MEMBER.equals(this);
    }

    public boolean isProductOwner() {
        return PRODUCT_OWNER.equals(this);
    }
}

src/main/webapp/WEB-INF/jsp/developer/team/my_team.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<!DOCTYPE HTML>
<html>
<head>
    <title><spring:message code="my.team.page.title" text="My Team"/></title>
</head>
<body>
<div class="row">
    <hr/>
    <div class="span3">
        <ul class="nav nav-tabs nav-stacked">
            <li>
                <a href="../my_profile">
                    <i class="icon-chevron-right pull-right"></i> <spring:message code="my.profile.page.menu.my.info" text="My-Info"/>
                </a>
            </li>
            <li>
                <a href="change_password">
                    <i class="icon-chevron-right pull-right"></i> <spring:message code="my.profile.page.menu.change.password" text="Change Password"/>
                </a>
            </li>
            <sec:authorize ifAnyGranted="ROLE_MASTER,ROLE_MEMBER">
                <li>
                    <a href="javascript:void(0)">
                        <strong>
                            <i class="icon-chevron-right pull-right"></i> <spring:message code="my.profile.page.menu.my.team" text="My Team"/>
                        </strong>
                    </a>
                </li>
            </sec:authorize>
        </ul>
    </div>
    <div class="span9">
        <c:if test="${not myTeamDto.referTeam}">
            <p class="text-error">
                <spring:message code="my.team.page.not.added" text="Not added any team yet"/>.
            </p>
        </c:if>
        <c:if test="${myTeamDto.referTeam}">
            <h2 class="text-error">${myTeamDto.teamName}</h2>
            <small class="muted">${myTeamDto.teamDescription}</small>
            <dl>
                <dt class="text-info"><i class="icon-user"></i> <spring:message code="my.team.page.members" text="Members"/></dt>
                <dd>
                    <ul>
                        <c:forEach items="${myTeamDto.members}" var="m">
                            <li>
                                <strong style="width: 150px;display: inline-block;">${m.showName}
                                    <span class="text-success">${m.scrumTerm.master?'(Master)':''}</span>
                                </strong>
                                <span style="width: 100px;display: inline-block;"
                                      title="Cell phone">${m.cellPhone}</span>
                                <span>${m.email}</span>
                            </li>
                        </c:forEach>
                    </ul>
                </dd>
            </dl>
            <dl>
                <dt class="text-info"><i class="icon-tasks"></i> <spring:message code="my.team.page.projects" text="Projects"/></dt>
                <dd>
                    <ul>
                        <c:forEach items="${myTeamDto.projects}" var="p">
                            <li><a href="../project_/overview?name=${p.name}">${p.name} (${p.code})</a>

                                <div class="muted" title="Project description">${p.description}</div>
                            </li>
                        </c:forEach>
                    </ul>
                </dd>
            </dl>
        </c:if>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/developer/team/team_form.jsp
<%--
  User: Shengzhao Li
  Date: 14-1-6
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
<head>
    <title><spring:message code="team.form.page.title" text="Team"/></title>
    <script src="${contextPath}/js/web/ckeditor/ckeditor.js"></script>
</head>
<body>
<div class="row">
    <hr/>
</div>

<form:form commandName="teamFormDto" id="teamForm">
    <form:hidden path="guid"/>
    <div class="row sprint-form">
        <div class="span8 well">
            <fieldset>
                <legend><spring:message code="team.form.page.title" text="Team"/></legend>
                <table class="width100">
                    <tr>
                        <td colspan="2">
                            <label for="name"><spring:message code="team.form.page.name" text="Team name"/></label>
                            <spring:message code="team.form.page.name.holder" text="Team name" var="teamNameHolderMessage"/>
                            <form:input path="name" id="name" placeholder="${teamNameHolderMessage}" required="true"
                                        maxlength="255" class="input-xxlarge"/>
                            <form:errors path="name" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="team.form.page.name.help" text="Please input the team name, required."/></span>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <c:forEach items="${teamFormDto.developerDtoGrouperList}" var="gd" varStatus="vs">
                                <label>${gd.key.label}</label>
                                <c:forEach items="${gd.results}" var="dev">
                                    <c:if test="${gd.key.master}">
                                        <form:checkbox path="masters" value="${dev.guid}"/> ${dev.showName}&nbsp;&nbsp;
                                    </c:if>
                                    <c:if test="${gd.key.member}">
                                        <form:checkbox path="members" value="${dev.guid}"/> ${dev.showName}&nbsp;&nbsp;
                                    </c:if>
                                </c:forEach>
                                ${vs.last?'':' <br/><br/>'}
                            </c:forEach>
                            <form:errors path="masters" cssClass="label label-warning"/>
                            <form:errors path="members" cssClass="label label-warning"/>
                            <span class="help-block"><spring:message code="team.form.page.members.help" text="Please choose the team persons, required."/></span>

                                <%--For bind if validation failed--%>
                            <c:forEach items="${teamFormDto.developerDtoList}" var="d" varStatus="s">
                                <form:hidden path="developerDtoList[${s.index}].guid"/>
                                <form:hidden path="developerDtoList[${s.index}].nickName"/>
                                <form:hidden path="developerDtoList[${s.index}].email"/>
                                <form:hidden path="developerDtoList[${s.index}].scrumTerm"/>
                            </c:forEach>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <label for="description"><spring:message code="team.form.page.description" text="Description"/></label>
                            <form:textarea path="description" cssClass="ckeditor" id="description"/>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </div>
        <div class="span3 well">
            <fieldset>
                <legend><spring:message code="team.form.page.team.projects" text="Team Projects"/></legend>
                <ul class="unstyled">
                    <c:forEach items="${teamFormDto.projects}" var="p">
                        <li>
                            <label class="checkbox">
                                <form:checkbox path="projectGuids" value="${p.guid}"/> ${p.name}(${p.code})
                            </label>
                        </li>
                    </c:forEach>

                        <%--For bind if validation failed--%>
                    <c:forEach items="${teamFormDto.projects}" var="d" varStatus="s">
                        <form:hidden path="projects[${s.index}].guid"/>
                        <form:hidden path="projects[${s.index}].name"/>
                        <form:hidden path="projects[${s.index}].code"/>
                    </c:forEach>
                    <li>
                        <form:errors path="projectGuids" cssClass="label label-warning"/>
                    </li>
                </ul>
                <span class="help-block"><spring:message code="team.form.page.team.projects.help" text="Please choose the team projects, optional."/></span>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class="span5 offset3">
            <button type="submit" class="btn btn-success btn-large"><i class="icon-plus icon-white"></i>
                <spring:message code="team.form.page.save" text="Save"/>
            </button>
            <a href="../overview" class="btn btn-link"><spring:message code="team.form.page.cancel" text="Cancel"/></a>
        </div>
    </div>
</form:form>
</body>
</html>